# Generated by Django 3.2 on 2021-07-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['manager']},
        ),
    ]
