# Generated by Django 3.2 on 2021-07-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_alter_artwork_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='cover',
            field=models.ImageField(default='hello', upload_to='cover/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='file',
            field=models.FileField(default='hello', upload_to='file/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
