# Generated by Django 3.2 on 2021-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to='singles/%Y/%m/%d/'),
        ),
    ]
