# Generated by Django 3.2 on 2021-07-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_residence_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='song',
        ),
    ]
